"""Render the evaluation JSON into a Markdown results table.

Generated, never hand-typed. A number in the write-up that was transcribed by
hand is a number that will eventually disagree with the file it came from.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import models, schema, splits

REPORTS_DIR = Path("reports")

SHORT = {"yield_strength": "YS", "tensile_strength": "UTS", "elongation": "EL"}
COMPONENT_OF = {"yield_strength": "yield_ratio", "tensile_strength": "tensile_strength",
                "elongation": "elongation"}


def _mae(bundle: dict, protocol: str, model: str, target: str, key: str = "full"):
    try:
        return bundle["protocols"][protocol]["models"][model]["landmarks"][target][key]["mae"]
    except (KeyError, TypeError):
        return None


def _fold_std(bundle: dict, protocol: str, model: str, target: str):
    """Fold-to-fold spread of the component that carries this landmark."""
    try:
        comp = bundle["protocols"][protocol]["models"][model]["components"][COMPONENT_OF[target]]
        return comp["summary_mae"]["std"], comp["summary_mae"]["n_folds"]
    except (KeyError, TypeError):
        return None, None


def _fmt(value, dp: int = 1) -> str:
    return "--" if value is None else f"{value:.{dp}f}"


def render(bundle: dict, manifest: dict) -> str:
    out: list[str] = []
    protocols = [p for p in splits.PROTOCOLS if p in bundle["protocols"]]
    model_names = [m for m in models.LADDER
                   if m in bundle["protocols"][protocols[0]]["models"]]

    out.append("# Results\n")
    out.append("Generated by `python -m stresspredict.report`. Do not edit by hand.\n")
    out.append(f"- Rows evaluated: **{bundle['n_rows_evaluated']}** "
               f"(`--rows {bundle['rows_filter']}`)")
    first = bundle["protocols"][protocols[0]]
    out.append(f"- Grades: **{first['n_grades']}**  |  "
               f"fully-observed core: **{first['n_common_core_rows']}** rows")
    out.append(f"- Parameterisation: `{first['parameterisation']}`  |  "
               f"features: `{first['feature_set']}`  |  "
               f"nested tuning: **{'on' if first['tuned_inside_outer_fold'] else 'off'}**")
    out.append(f"- Source: `{manifest.get('source_id')}` sha256 "
               f"`{str(manifest.get('raw_sha256'))[:16]}...`\n")

    # --- the physical floor -------------------------------------------
    out.append("## The physical floor\n")
    out.append("Within-composition spread on **measured rows only** -- the error a perfect")
    out.append("composition-only model would still make, because the rows inside each group")
    out.append("differ by processing the features cannot see. The two columns bracket the")
    out.append("true floor from below (in-sample) and above (leave-one-out).\n")
    out.append("| Target | Floor (in-sample) | Floor (LOO) | Groups | Rows | Pooled-with-spec-minima (deflated) |")
    out.append("|---|---|---|---|---|---|")
    for target in schema.TARGETS:
        strata = manifest["noise_floor"]["targets"][target]
        m, a = strata["measured_only"], strata["all_rows"]
        unit = schema.TARGET_UNITS[target]
        if not m.get("n_groups"):
            out.append(f"| {target} | -- | -- | 0 | 0 | -- |")
            continue
        out.append(
            f"| {target} | {_fmt(m['mae_floor_insample'], 1)} {unit} | "
            f"{_fmt(m['mae_floor_loo'], 1)} {unit} | {m['n_groups']} | {m['n_rows']} | "
            f"{_fmt(a.get('mae_floor_insample'), 1)} {unit} |"
        )
    out.append("")

    # --- main table ----------------------------------------------------
    out.append("## MAE by protocol, model and target\n")
    out.append("MAE is primary: the targets are modelled through a log link, so inverting a")
    out.append("prediction recovers the conditional median, which is the quantity MAE scores.\n")
    for protocol in protocols:
        res = bundle["protocols"][protocol]
        flag = "  **(LEAKY -- upper bound only)**" if res["protocol_is_leaky"] else ""
        out.append(f"### `{protocol}`{flag}\n")
        out.append(f"*{res['protocol_question']}*\n")
        header = "| Model | " + " | ".join(
            f"{SHORT[t]} MAE ({schema.TARGET_UNITS[t]})" for t in schema.TARGETS
        ) + " | folds |"
        out.append(header)
        out.append("|---|" + "---|" * (len(schema.TARGETS) + 1))
        for model in model_names:
            cells = []
            n_folds = None
            for target in schema.TARGETS:
                mae = _mae(bundle, protocol, model, target)
                std, nf = _fold_std(bundle, protocol, model, target)
                n_folds = n_folds or nf
                cells.append(_fmt(mae) + (f" ± {_fmt(std)}" if std is not None else ""))
            out.append(f"| `{model}` | " + " | ".join(cells) + f" | {n_folds or '--'} |")
        out.append("")
        excluded = (res["models"][model_names[0]]["components"]
                    .get("tensile_strength", {}).get("excluded_small_groups"))
        if excluded:
            out.append("Families too small to hold out (kept in training): "
                       + ", ".join(f"`{k}` ({v} rows)" for k, v in excluded.items()) + "\n")

    # --- like-for-like against the floor --------------------------------
    headline = splits.HEADLINE_PROTOCOL
    if headline in bundle["protocols"]:
        out.append("## Model error vs the floor, on matching rows\n")
        out.append("The floor is measured on **measured rows only**, so the model has to be")
        out.append("scored on measured rows only too. An all-rows model MAE compared against a")
        out.append("measured-only floor appears to beat a physical limit -- which is a sign of a")
        out.append("mismatched comparison, not of a good model.\n")
        out.append("| Target | Floor (measured rows) | Best model, measured rows "
                   "| Best model, spec minima |")
        out.append("|---|---|---|---|")
        for target in schema.TARGETS:
            fl = manifest["noise_floor"]["targets"][target]["measured_only"]
            unit = schema.TARGET_UNITS[target]
            best_measured, best_spec = None, None
            for model in model_names:
                if model == "dummy":
                    continue
                try:
                    by_kind = (bundle["protocols"][headline]["models"][model]
                               ["landmarks"][target]["by_measurement_kind"])
                except (KeyError, TypeError):
                    continue
                measured = by_kind.get("measured", {}).get("mae")
                spec = by_kind.get("spec_minimum", {}).get("mae")
                if measured is not None and (best_measured is None or measured < best_measured[0]):
                    best_measured = (measured, model)
                if spec is not None and (best_spec is None or spec < best_spec[0]):
                    best_spec = (spec, model)
            if best_measured is None:
                continue
            floor_txt = (
                f"{_fmt(fl.get('mae_floor_insample'))} .. {_fmt(fl.get('mae_floor_loo'))} {unit}"
                if fl.get("n_groups") else "not measurable"
            )
            spec_txt = f"{_fmt(best_spec[0])} (`{best_spec[1]}`)" if best_spec else "--"
            out.append(f"| {target} | {floor_txt} | "
                       f"{_fmt(best_measured[0])} (`{best_measured[1]}`) | {spec_txt} |")
        out.append("")

    # --- the leak ------------------------------------------------------
    if "random_kfold" in bundle["protocols"] and "gkf_grade" in bundle["protocols"]:
        out.append("## What grade leakage is worth\n")
        out.append("The difference between a random split and a grade-grouped split, on the")
        out.append("same rows and the same models. The right-hand column is the honest one.\n")
        out.append("| Model | Target | Random K-fold (leaky) | Grade-grouped | Inflation |")
        out.append("|---|---|---|---|---|")
        for model in model_names:
            for target in schema.TARGETS:
                leaky = _mae(bundle, "random_kfold", model, target)
                honest = _mae(bundle, "gkf_grade", model, target)
                if leaky is None or honest is None or not leaky:
                    continue
                out.append(f"| `{model}` | {SHORT[target]} | {_fmt(leaky)} | {_fmt(honest)} "
                           f"| {honest / leaky:.2f}x |")
        out.append("")

    # --- correctness ---------------------------------------------------
    sign = bundle["ridge_sign_check"]
    out.append("## Correctness checks\n")
    out.append(f"**Ridge coefficient signs: {'PASS' if sign['all_passed'] else 'FAIL'}** "
               "-- a wiring test, not a performance metric.\n")
    out.append("| Component | Expectation | Carbon coefficient | Result |")
    out.append("|---|---|---|---|")
    for e in sign["expectations"]:
        out.append(f"| {e['component']} | {e['expected']} | {e['observed']:+.4f} | "
                   f"{'pass' if e['passed'] else 'FAIL'} |")
    out.append("")

    out.append("**Physical invariant (UTS > YS) on out-of-fold predictions:**\n")
    out.append("| Protocol | Model | Checked | Violations |")
    out.append("|---|---|---|---|")
    for protocol in protocols:
        for model in model_names:
            inv = bundle["protocols"][protocol]["models"][model].get("invariant_uts_gt_ys")
            if inv:
                out.append(f"| `{protocol}` | `{model}` | {inv['n_checked']} | "
                           f"**{inv['violations']}** |")
    out.append("")
    return "\n".join(out)


def merge(bundles: list[dict]) -> dict:
    """Combine per-protocol runs into one bundle.

    The protocols are independent -- same seed, same rows, same models -- so
    running them as four processes and merging gives byte-identical numbers to
    one `--protocol all` invocation, in a quarter of the wall time. Everything
    outside `protocols` must agree, and a mismatch raises rather than silently
    picking one, because a merged report whose halves came from different feature
    sets would be worse than no report.
    """
    if not bundles:
        raise ValueError("nothing to merge")
    merged = dict(bundles[0])
    merged["protocols"] = {}
    for bundle in bundles:
        for key in ("rows_filter", "restrict_ht_rows", "n_rows_evaluated"):
            if bundle[key] != merged[key]:
                raise ValueError(
                    f"refusing to merge: {key} differs "
                    f"({bundle[key]!r} vs {merged[key]!r})"
                )
        for name, result in bundle["protocols"].items():
            for key in ("parameterisation", "feature_set", "seed"):
                first = next(iter(merged["protocols"].values()), None)
                if first is not None and result[key] != first[key]:
                    raise ValueError(f"refusing to merge: {key} differs across runs")
            merged["protocols"][name] = result
    return merged


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render evaluation JSON to Markdown.")
    ap.add_argument("--report", type=Path, nargs="+",
                    default=[REPORTS_DIR / "eval_ratio_comp_all.json"],
                    help="one bundle, or several per-protocol bundles to merge")
    ap.add_argument("--manifest", type=Path, default=Path("data/processed/data_manifest.json"))
    ap.add_argument("--out", type=Path, default=REPORTS_DIR / "results.md")
    ap.add_argument("--merged-out", type=Path, default=None,
                    help="also write the merged bundle here")
    args = ap.parse_args(argv)

    bundle = merge([json.loads(p.read_text(encoding="utf-8")) for p in args.report])
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))

    if args.merged_out is not None:
        args.merged_out.write_text(json.dumps(bundle, indent=2), encoding="utf-8")
        print(f"wrote {args.merged_out}")

    args.out.write_text(render(bundle, manifest), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
